baseURL = "https://occb.dev/"
languageCode = "en-us"
title = "Olli On Tour"
theme = "occb"

copyright = "2020-{year}"

[params]
  favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[build]
  writeStats = true